server:
  port: 8086
spring:
  datasource:
    url: r2dbc:postgresql://localhost:8080/User
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#  data:
#    mongodb:
#      database: AlSudaisFlowForContractWithMobileScreens
##      username: admin
##      password: root
##      host: mongo
#      host: localhost
#      port: 27017

time-window: 10000

#camel:
#  component:
#    kafka:
#      brokers: localhost:9092