#version: "3"
#services:
#  mongo:
#    image: mongo:latest
#    container_name: mongo
#    ports:
#      - 27017:27017
#    restart: always
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
#      ME_CONFIG_MONGODB_ADMINPASSWORD: root
#      ME_CONFIG_MONGODB_SERVER: mongodb
#  user-container:
#    image: camel.jar
#    restart: on-failure
#    container_name: user-container
#    ports:
#      - 8086:8086
#    links:
#      - mongo

version: '1'
services:
  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    ports :
      - '2181:2181'
#    volumes :
#      - 'zookeeper_data:/bitnami '
    environment:
      -  ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'docker.io/bitnami/kafka:2-debian-10'
    ports :
      - '9092:9092'
#    volumes :
#      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_HOSTNAME=docker.for.win.localhost
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local